[package]
name = "chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
once_cell = "1.10.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
smallvec = { version = "1.8.0", features = ["const_generics"] }
structopt = "0.3.26"
tap = "1.0.1"
tinyvec = { version = "1.5.1", features = ["alloc"] }
